### ISSUE TITLE
Application crashes after base camps are getting empty

### ISSUE THREAD

**Issue by amit3334** [panyz522/CS561-HalmaEditor#3]
[input.txt](https://github.com/panyz522/CS561-HalmaEditor/files/3747693/input.txt)
Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\Users\Amit Sankhla\OneDrive - University of Southern California\Documents\Programs\output.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at HalmaEditor.Data.OutputManager.OnChanged(Object sender, FileSystemEventArgs e) in C:\Users\Turnip\source\repos\HalmaEditor\Data\OutputManager.cs:line 70
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

Please run the attached input.txt file. Checked it multiple times and whenever the base camp of either Black or White gets empty, the application crashes with the above error.

**Comment by panyz522** [comment]
Try to put your input.txt and output.txt outside of onedrive/googledrive/dropbox folder. It may cause issues when the input/output file is changed and onedrive synchronizer starts synchronizing the file but the editor is also trying to read it.

It's a good practice to use git/p4v... for backup instead of put all of your project content in the cloud drive.

**Comment by amit3334** [comment]
I even tried putting the files on my local. Still getting the same issue. I have run the code on my local and the output.txt contains the correct result. I am not sure why its not getting picked up by the editor.

Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\HW2\output.txt' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at HalmaEditor.Data.OutputManager.OnChanged(Object sender, FileSystemEventArgs e) in C:\Users\Turnip\source\repos\HalmaEditor\Data\OutputManager.cs:line 70
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

**Comment by panyz522** [comment]
Sounds weird. It works on my PC and some of my friends'. The editor cannot read the file since it was used by another process. Did you try to find what process was using the file? https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows

**Comment by panyz522** [comment]
Hi! I reproduced the issue when I was developing a new feature. Please check the newest release~

**Comment by amit3334** [comment]
Great. I'll check let you know.
